services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    entrypoint: ["sh", "docker/entrypoint.sh"]
    env_file:
      - .env
